server:
  port: 9700
logging:
#  level:
    # package com.uto.suhuanyuan 包下的所有程序设为info等级,logback配置文件中会起作用,这个不起作用
#    com.uto.suhuanyuan: info
  logback:
    rollingpolicy:
      max-history: 30
      max-file-size: 50MB
  file:
    path: ./logs
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
  mapper-locations: classpath:mapper/*.xml
  #实体扫描,多个包用逗号隔开
  type-aliases-package: com.richard.entity
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      db-type: sql_server
      table-underline: true
spring:
  profiles:
    active: ${profileActive}
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    initialization-mode: always
    continue-on-error: true
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: ProjectPool
      max-lifetime: 30000
      connection-timeout: 30000
  mvc:
    static-path-pattern: /**
#jasypt:
#  encryptor:
#    property:
#      prefix: encryption(
#      suffix: )
#    bean: codeSheepEncryptorBean


---
#测试部署环境
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    dynamic:
      primary: NCC2111
      strict: false
      datasource:
        NCC2111:
          url: jdbc:sqlserver://192.168.20.30:1433;database=flag_test
          username: sa
          password: P@ssw0rd
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl